#!/usr/bin/env python3
"""Dump the golden latent->RGB projections used by the video denoise preview.

`src/fixtures/latent_rgb.json` is produced by INSTANTIATING ComfyUI's own
`comfy/latent_formats.py` classes and running its own
`latent_preview.Latent2RGBPreviewer` over a pinned latent -- never by retyping
the tables here. A transcription checked against its own transcription proves
nothing, and the whole point of this file is that the numbers in `src/preview.zig`
are a published fit rather than something we invented.

Two maps are dumped, one per video backend mlx-serve serves:

  * `ltx_av`  <- `LTXAV`, 128 channels. This is the LTX-2 map, NOT `LTXV`.
    LTX-2 kept LTX-0.9's geometry (128 channels, 32x32x8) and replaced the
    latent space: ComfyUI shipped `class LTXAV(LTXV): pass` on 2026-01-05 and
    blanked the inherited factors one day later rather than ship a wrong
    preview, then landed this fitted table on 2026-08-01. The two tables are
    orthogonal (cosine -0.04 over all 384 coefficients), so reusing the 0.9
    numbers on a 2.x pack is the failure this comment exists to prevent.
  * `minimax_h3` <- `MiniMaxH3Video`, 24 channels.

Both were fit against the NORMALIZED latent -- ComfyUI's VAEs apply
`(x - latents_mean) / latents_std` inside encode and undo it inside decode, so
the sampler-space latent its previewer sees is the same space our DiTs work in.
That is why the projection applies to our x0 prediction directly.

The pinned latent is generated by an integer LCG and f32-only arithmetic so the
Zig side can regenerate the SAME bytes without the values living in the fixture
(`pinnedLatent` in src/preview.zig). Each case carries MORE pixels than the map
has channels, so the reference's own output over-determines every coefficient:
a single wrong number in `src/latent_rgb.zig` cannot cancel across the case.

`--zig-out` writes `src/latent_rgb.zig` from the same tables, so the numbers the
engine reads are never hand-transcribed either.

Usage:
    uv run --with torch --with numpy --with pillow \\
        tests/dump_latent_rgb_factors.py \\
        --ref ~/claude-tmp/latent-rgb-ref \\
        --out src/fixtures/latent_rgb.json --zig-out src/latent_rgb.zig

Refresh the sources with:
    mkdir -p ~/claude-tmp/latent-rgb-ref
    for f in comfy/latent_formats.py latent_preview.py; do
      curl -sL "https://raw.githubusercontent.com/comfyanonymous/ComfyUI/master/$f" \\
        -o ~/claude-tmp/latent-rgb-ref/$(basename $f)
    done
    git ls-remote https://github.com/comfyanonymous/ComfyUI.git refs/heads/master
"""

import argparse
import importlib.util
import json
import os
import sys
import types


class _Exploding(types.ModuleType):
    """Stub that raises on ANY attribute access.

    A stub returning MagicMock would let a golden value be produced by a mock
    instead of by the reference, which is exactly the failure this file exists
    to prevent.
    """

    def __getattr__(self, name):
        # Dunders must behave like an ordinary missing attribute: torch's own
        # import machinery walks sys.modules probing `__file__`/`__path__`, and
        # exploding there says nothing about the reference reaching our stub.
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)
        raise AssertionError(
            f"reference reached stubbed {self.__name__}.{name} -- that code path "
            "is not part of the latent->RGB projection, so its output is not a "
            "valid golden value"
        )


def _register(name, mod):
    """Publish a module AND bind it on its parent.

    `import comfy.model_management` binds only `comfy` in the importing
    namespace, so the reference reaches the submodule as an ATTRIBUTE of the
    parent -- a parent that is itself an exploding stub would then swallow
    every child. Parents are therefore plain modules; only the leaves we want
    unreachable explode.
    """
    sys.modules[name] = mod
    if "." in name:
        parent_name, _, leaf = name.rpartition(".")
        parent = sys.modules.get(parent_name)
        if parent is None or isinstance(parent, _Exploding):
            parent = types.ModuleType(parent_name)
            _register(parent_name, parent)
        setattr(parent, leaf, mod)

    return mod


def _stub(*names):
    for n in names:
        if n not in sys.modules:
            _register(n, _Exploding(n))


def _named(name, **attrs):
    """A real module carrying only the names the reference BINDS but never uses
    to compute a value (CLI defaults, the TAESD/VAE classes `get_previewer`
    picks between). Binding them to None means nothing here can produce a
    number -- unlike a mock, which could."""
    mod = types.ModuleType(name)
    for k, v in attrs.items():
        setattr(mod, k, v)

    return _register(name, mod)


def load_reference(ref_dir):
    """Import `latent_formats` and `latent_preview` with ComfyUI stubbed out."""
    formats_path = os.path.join(ref_dir, "latent_formats.py")
    preview_path = os.path.join(ref_dir, "latent_preview.py")
    for p in (formats_path, preview_path):
        if not os.path.exists(p):
            raise SystemExit(f"missing reference source: {p}")

    _stub("comfy.nested_tensor", "comfy.utils", "folder_paths")

    # `preview_to_image` asks these two questions about the MACHINE, not about
    # the projection. Answering them is not producing a golden value.
    _named("comfy.model_management",
           directml_enabled=False,
           device_supports_non_blocking=lambda device: False)
    # Only `get_previewer` reads these, and we never call it.
    _named("comfy.cli_args",
           args=types.SimpleNamespace(preview_method=None, preview_size=512),
           LatentPreviewMethod=None)
    _named("comfy.taesd.taesd", TAESD=None)
    _named("comfy.sd", VAE=None)

    def _load(path, name):
        spec = importlib.util.spec_from_file_location(name, path)
        mod = importlib.util.module_from_spec(spec)
        sys.modules[name] = mod
        spec.loader.exec_module(mod)

        return mod

    formats = _load(formats_path, "comfy_latent_formats")
    preview = _load(preview_path, "comfy_latent_preview")

    return formats, preview


def pinned_latent(np, c, t, h, w, salt):
    """The same volume src/preview.zig's `pinnedLatent` builds.

    Integer LCG then f32-only arithmetic: a 24-bit numerator over 2^24 is exact
    in f32, so every operation below is a single IEEE-754 single-precision op
    and both languages land on identical bits. Range [-1.5, 1.5) stands in for
    a unit-variance normalized latent.
    """
    n = c * t * h * w
    x = (0x9E3779B9 ^ salt) & 0xFFFFFFFF
    raw = np.empty(n, dtype=np.uint32)
    for i in range(n):
        x = (x * 1664525 + 1013904223) & 0xFFFFFFFF
        raw[i] = x >> 8
    v = raw.astype(np.float32)
    v = v / np.float32(16777216.0)
    v = v * np.float32(3.0)
    v = v - np.float32(1.5)
    assert v.dtype == np.float32

    return v.reshape(1, c, t, h, w)


def dump_case(torch, np, preview_mod, fmt, name, c, t, h, w, salt):
    """Run the reference previewer and capture BOTH its float projection and
    its uint8 image. The float tensor is taken by spying on the reference's own
    `preview_to_image` call rather than recomputing the linear here."""
    previewer = preview_mod.Latent2RGBPreviewer(
        fmt.latent_rgb_factors,
        fmt.latent_rgb_factors_bias,
        getattr(fmt, "latent_rgb_factors_reshape", None),
    )
    captured = {}
    original = preview_mod.preview_to_image

    def spy(latent_image, do_scale=True):
        captured["f32"] = latent_image.detach().to(torch.float32).clone()

        return original(latent_image, do_scale)

    preview_mod.preview_to_image = spy
    try:
        lat = torch.from_numpy(pinned_latent(np, c, t, h, w, salt))
        image = previewer.decode_latent_to_preview(lat)
    finally:
        preview_mod.preview_to_image = original

    if "f32" not in captured:
        raise SystemExit("the reference never reached preview_to_image")
    rgb_f32 = captured["f32"].numpy()
    rgb_u8 = np.asarray(image)
    if rgb_f32.shape != (h, w, 3) or rgb_u8.shape != (h, w, 3):
        raise SystemExit(f"unexpected reference shapes {rgb_f32.shape} / {rgb_u8.shape}")

    return {
        "map": name,
        "c": c, "t": t, "h": h, "w": w,
        "salt": salt,
        # The reference previewer always projects temporal index 0 (`x0[0,:,0]`).
        "ti": 0,
        "rgb_f32": [float(x) for x in rgb_f32.reshape(-1)],
        "rgb_u8": [int(x) for x in rgb_u8.reshape(-1)],
    }


def dump_map(fmt, cls_name):
    factors = fmt.latent_rgb_factors
    bias = fmt.latent_rgb_factors_bias
    if factors is None or bias is None:
        raise SystemExit(f"{cls_name} carries no latent_rgb_factors -- do not invent one")
    if getattr(fmt, "latent_rgb_factors_reshape", None) is not None:
        raise SystemExit(f"{cls_name} needs a pixel-unshuffle reshape, which src/preview.zig does not implement")
    if len(bias) != 3 or any(len(f) != 3 for f in factors):
        raise SystemExit(f"{cls_name}: factors must be [C][3] with a [3] bias")

    return {
        "class": cls_name,
        "channels": len(factors),
        "factors": [[float(v) for v in row] for row in factors],
        "bias": [float(v) for v in bias],
    }


ZIG_HEADER = '''//! Published latent -> RGB projections for the video denoise preview.
//!
//! GENERATED by `tests/dump_latent_rgb_factors.py` from ComfyUI's own
//! `comfy/latent_formats.py` (GPL-3.0, see NOTICE) -- do not hand-edit. Both
//! tables are least-squares fits published upstream, not something we derived;
//! `src/fixtures/latent_rgb.json` pins these numbers and the projection they
//! produce against the reference's own output (`latent2rgb fixtures` in
//! src/preview.zig).
//!
//! Reference: {repo}
//! Commit:    {commit}

/// `factors[c] = .{{ r, g, b }}` for latent channel `c`, plus a constant bias.
/// The projection is `rgb[k] = sum_c latent[c] * factors[c][k] + bias[k]`, whose
/// output range is calibrated for `(rgb + 1) / 2` -- there is no per-frame
/// contrast stretch to apply on top, and adding one would undo the fit.
pub const Map = struct {{
    /// Upstream class name, for the log line and the fixture key.
    name: []const u8,
    factors: []const [3]f32,
    bias: [3]f32,

    pub fn channels(self: Map) u32 {{
        return @intCast(self.factors.len);
    }}
}};
'''


def emit_zig(path, maps, reference):
    parts = [ZIG_HEADER.format(repo=reference["repo"], commit=reference["commit"] or "unknown")]
    for key, m in maps.items():
        rows = "".join(
            "    .{{ {:>12}, {:>12}, {:>12} }},\n".format(*(f"{v:.6f}" for v in row))
            for row in m["factors"]
        )
        bias = ", ".join(f"{v:.6f}" for v in m["bias"])
        parts.append(
            f"\n/// `{m['class']}`, {m['channels']} channels.\n"
            f"pub const {key}: Map = .{{\n"
            f'    .name = "{m["class"]}",\n'
            f"    .factors = &{key}_factors,\n"
            f"    .bias = .{{ {bias} }},\n"
            "};\n"
            f"\nconst {key}_factors = [{m['channels']}][3]f32{{\n{rows}}};\n"
        )
    with open(os.path.expanduser(path), "w") as f:
        f.write("".join(parts))

    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", required=True, help="directory holding the two reference sources")
    ap.add_argument("--out", required=True)
    ap.add_argument("--zig-out", default="", help="also write the Zig table (src/latent_rgb.zig)")
    ap.add_argument("--ref-commit", default="", help="ComfyUI commit the sources were fetched at")
    args = ap.parse_args()

    import numpy as np
    import torch

    formats, preview_mod = load_reference(os.path.expanduser(args.ref))

    maps = {
        "ltx_av": dump_map(formats.LTXAV(), "LTXAV"),
        "minimax_h3": dump_map(formats.MiniMaxH3Video(), "MiniMaxH3Video"),
    }
    if maps["ltx_av"]["channels"] != 128:
        raise SystemExit("LTXAV is no longer 128-channel -- our LTX packs are")
    if maps["minimax_h3"]["channels"] != 24:
        raise SystemExit("MiniMaxH3Video is no longer 24-channel -- our H3 packs are")
    if maps["ltx_av"]["factors"] == formats.LTXV().latent_rgb_factors:
        raise SystemExit(
            "LTXAV's factors equal LTXV's -- upstream has re-inherited the "
            "LTX-0.9 table, which is the wrong latent space for a 2.x pack"
        )

    # h*w MUST exceed the channel count: with fewer pixels than channels the
    # reference's output is an underdetermined system and a compensating pair of
    # wrong coefficients could cancel across every pixel in the case.
    cases = [
        dump_case(torch, np, preview_mod, formats.LTXAV(), "ltx_av", 128, 3, 12, 16, 1),
        dump_case(torch, np, preview_mod, formats.MiniMaxH3Video(), "minimax_h3", 24, 5, 8, 12, 2),
    ]
    for c in cases:
        if c["h"] * c["w"] <= maps[c["map"]]["channels"]:
            raise SystemExit(f"case {c['map']}: {c['h']}x{c['w']} does not over-determine "
                             f"{maps[c['map']]['channels']} channels")

    out = {
        "_comment": [
            "GOLDEN VALUES -- generated, do not hand-edit.",
            "Produced by executing ComfyUI's own latent_formats classes and",
            "latent_preview.Latent2RGBPreviewer over a pinned latent.",
            "ltx_av is LTXAV (LTX-2), NOT LTXV (LTX-0.9): same geometry, different latent space.",
        ],
        "_generator": "tests/dump_latent_rgb_factors.py",
        "_reference": {
            "repo": "https://github.com/comfyanonymous/ComfyUI",
            "license": "GPL-3.0",
            "commit": args.ref_commit,
            "files": ["comfy/latent_formats.py", "latent_preview.py"],
        },
        "maps": maps,
        "cases": cases,
    }
    with open(os.path.expanduser(args.out), "w") as f:
        json.dump(out, f, indent=1)
        f.write("\n")
    print(f"wrote {args.out}: {len(maps)} maps, {len(cases)} cases")
    if args.zig_out:
        print(f"wrote {emit_zig(args.zig_out, maps, out['_reference'])}")


if __name__ == "__main__":
    main()
